import { chromium } from '@playwright/test';
import { readFileSync, writeFileSync } from 'node:fs';

const guide = readFileSync('docs/TEST_ENVIRONMENT.md', 'utf8');
const password = guide.split('\n').find(line => line.includes('Presentation password for every account'))?.match(/`([^`]+)`/)?.[1];
if (!password) throw new Error('The local presentation credential is missing.');
const browser = await chromium.launch({ executablePath: 'C:/Program Files/Google/Chrome/Application/chrome.exe' });
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
const failures = [];
page.on('pageerror', error => failures.push(error.message));
await page.goto('http://localhost:5174/signin');
await page.locator('#email').fill('demo-makati-admin@kamoti.invalid');
await page.locator('#password').fill(password);
await page.locator('button[type="submit"]').click();
await page.waitForURL(url => !url.pathname.includes('signin'));
await page.goto('http://localhost:5174/admin/users');
await page.getByRole('button', { name: 'Change role', exact: true }).first().waitFor();
await page.screenshot({ path: 'tests/evidence/pills-users-toolbar-2026-10-04/before-users-desktop.png', fullPage: false });
const allRows = await page.locator('tbody > tr').count();
await page.locator('#role-filter').selectOption('admin');
await page.waitForResponse(response => response.url().includes('/api/admin/users') && response.request().method() === 'GET');
await page.getByText('This is your own account.').waitFor();
const self = page.locator('tbody > tr').filter({ hasText: 'This is your own account.' });
const selfRoleDisabled = await self.getByRole('button', { name: 'Change role', exact: true }).isDisabled();
await page.getByRole('button', { name: 'New account', exact: true }).click();
await page.locator('#new-email').fill('invalid');
await page.locator('#new-email').blur();
await page.locator('#new-email-note[role="alert"]').waitFor();
const invalidCreateDisabled = await page.getByRole('button', { name: 'Create account', exact: true }).isDisabled();
await page.setViewportSize({ width: 375, height: 812 });
await page.getByRole('button', { name: 'Close', exact: true }).click();
await page.screenshot({ path: 'tests/evidence/pills-users-toolbar-2026-10-04/before-users-mobile.png', fullPage: true });
writeFileSync('tests/evidence/pills-users-toolbar-2026-10-04/baseline.json', JSON.stringify({ allRows, selfRoleDisabled, invalidCreateDisabled, failures }, null, 2));
await browser.close();
